# -*- coding: utf-8 -*-
"""atm_card.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ytMLHxKeUiZqMS4APS78mFjcCkWecJin
"""

class ATMcard:
    def __init__(self, defaultPin, defaultBalance):
        self.defaultPin = defaultPin
        self.defaultBalance = defaultBalance

    def cekAwal(self):
        return self.defaultPin

    def cekSaldoAwal(self):
        return self.defaultBalance